import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { PageHeader } from "@/components/common/PageHeader";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { Pagination } from "@/components/common/Pagination";
import { Skeleton } from "@/components/ui/Skeleton";
import { Button } from "@/components/ui/Button";
import { AuditLogList } from "@/features/audit-logs/AuditLogList";
import { LogDetailsDialog } from "@/features/audit-logs/LogDetailsDialog";
import { auditLogsApi } from "@/features/audit-logs/api";
import { ApiError } from "@/lib/api";
import { DEFAULT_PAGE_SIZE } from "@/lib/constants";
import type { LogSchema, PageResponse } from "@/types/api";

export default function AuditLogsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const page = Math.max(1, Number(searchParams.get("page") ?? "1"));

  const [data, setData] = useState<PageResponse<LogSchema> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedLog, setSelectedLog] = useState<LogSchema | null>(null);

  const load = useCallback(async (targetPage: number) => {
    setLoading(true);
    setError(null);
    try {
      const res = await auditLogsApi.list(targetPage, DEFAULT_PAGE_SIZE);
      setData(res);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Couldn't load audit logs.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load(page);
  }, [page, load]);

  function goToPage(p: number) {
    setSearchParams((prev) => {
      const next = new URLSearchParams(prev);
      next.set("page", String(p));
      return next;
    });
  }

  return (
    <div>
      <PageHeader title="Audit Logs" description="Review security events generated by AegisLLM." />

      {loading && (
        <div className="space-y-2">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-[72px]" />
          ))}
        </div>
      )}

      {!loading && error && <ErrorState message={error} onRetry={() => load(page)} />}

      {!loading && !error && data && data.items.length === 0 && (
        <EmptyState
          title="No audit logs yet"
          description="Run a prompt through the Inspector to start building your security history."
          action={
            <Link to="/app/inspector">
              <Button size="sm">Open Inspector</Button>
            </Link>
          }
        />
      )}

      {!loading && !error && data && data.items.length > 0 && (
        <div className="flex flex-col gap-4">
          <AuditLogList logs={data.items} onSelect={setSelectedLog} />
          <Pagination page={data.page} pages={data.pages} total={data.total} onPageChange={goToPage} />
        </div>
      )}

      {selectedLog && <LogDetailsDialog log={selectedLog} onClose={() => setSelectedLog(null)} />}
    </div>
  );
}
